import { useCallback, useEffect, useMemo, useState } from 'react'
import Icon from './Icon'
import { getDynamicNodeFieldDefs } from '../config/viewConfig'
import {
  bulkCreateRows,
  createTableRow,
  deleteTableRow,
  fetchTableRows,
  updateTableRow,
} from '../api/client'

export type TableName = 'modules' | 'viewpoints' | 'nav_nodes' | 'edges' | 'node_logs'
export type AdminTab = TableName | 'bulk_csv'

interface ColumnDef {
  key: string
  label: string
  type: 'text' | 'number' | 'select'
  options?: Array<{ value: string; label: string }>
  relationalTable?: TableName
  required?: boolean
  autoGenerated?: boolean
}

interface TableSchema {
  name: TableName
  label: string
  primaryKey: string
  columns: ColumnDef[]
}

function buildNavNodeColumns(): ColumnDef[] {
  const dynamicDefs = getDynamicNodeFieldDefs()
  const fixedPrefix: ColumnDef[] = [
    { key: 'id', label: 'Node ID', type: 'text', required: true },
    { key: 'label', label: 'Node Label', type: 'text', required: true },
    {
      key: 'kind',
      label: 'Kind',
      type: 'select',
      options: [
        { value: 'folder', label: 'Folder' },
        { value: 'item', label: 'Item / Job' },
      ],
      required: true,
    },
    {
      key: 'parent_id',
      label: 'Parent Node',
      type: 'select',
      relationalTable: 'nav_nodes',
    },
  ]

  const dynamicColumns: ColumnDef[] = dynamicDefs.map((f) => {
    let colType: 'text' | 'number' | 'select' = 'text'
    let options: Array<{ value: string; label: string }> | undefined

    if (f.key === 'runs' || f.key === 'sort_order') {
      colType = 'number'
    } else if (f.key === 'status') {
      colType = 'select'
      options = [
        { value: 'ok', label: 'Healthy (ok)' },
        { value: 'warning', label: 'Degraded (warning)' },
        { value: 'danger', label: 'Unreachable (danger)' },
      ]
    } else if (f.key === 'node_kind' || f.key === 'kind') {
      colType = 'select'
      options = [
        { value: 'Service', label: 'Service' },
        { value: 'Source', label: 'Source' },
        { value: 'Process', label: 'Process' },
        { value: 'Store', label: 'Store' },
        { value: 'Sink', label: 'Sink' },
      ]
    }

    return {
      key: f.key,
      label: f.label,
      type: colType,
      options,
    }
  })

  // Ensure sort_order is present if not in dynamicDefs
  if (!dynamicColumns.some((c) => c.key === 'sort_order')) {
    dynamicColumns.push({ key: 'sort_order', label: 'Sort Order', type: 'number' })
  }

  return [...fixedPrefix, ...dynamicColumns]
}

function getSchemas(): TableSchema[] {
  return [
    {
      name: 'modules',
      label: 'Modules',
      primaryKey: 'id',
      columns: [
        { key: 'id', label: 'ID', type: 'text', required: true },
        { key: 'label', label: 'Label / Name', type: 'text', required: true },
      ],
    },
    {
      name: 'viewpoints',
      label: 'Viewpoints',
      primaryKey: 'id',
      columns: [
        { key: 'id', label: 'ID', type: 'text', required: true },
        {
          key: 'module_id',
          label: 'Module',
          type: 'select',
          relationalTable: 'modules',
          required: true,
        },
        { key: 'label', label: 'Label', type: 'text', required: true },
        { key: 'description', label: 'Description', type: 'text' },
        { key: 'folder', label: 'Folder Path', type: 'text' },
        { key: 'job_count', label: 'Job Count', type: 'number' },
      ],
    },
    {
      name: 'nav_nodes',
      label: 'Navigation Nodes',
      primaryKey: 'id',
      columns: buildNavNodeColumns(),
    },
    {
      name: 'edges',
      label: 'Edges (Dependencies)',
      primaryKey: 'id',
      columns: [
        { key: 'id', label: 'Edge ID', type: 'text', required: true },
        {
          key: 'source',
          label: 'Source Node',
          type: 'select',
          relationalTable: 'nav_nodes',
          required: true,
        },
        {
          key: 'target',
          label: 'Target Node',
          type: 'select',
          relationalTable: 'nav_nodes',
          required: true,
        },
      ],
    },
    {
      name: 'node_logs',
      label: 'Node Logs',
      primaryKey: 'id',
      columns: [
        { key: 'id', label: 'Log ID', type: 'number', autoGenerated: true },
        {
          key: 'node_id',
          label: 'Node',
          type: 'select',
          relationalTable: 'nav_nodes',
          required: true,
        },
        { key: 'timestamp', label: 'Timestamp', type: 'text', required: true },
        {
          key: 'level',
          label: 'Level',
          type: 'select',
          options: [
            { value: 'INFO', label: 'INFO' },
            { value: 'WARN', label: 'WARN' },
            { value: 'ERROR', label: 'ERROR' },
          ],
          required: true,
        },
        { key: 'message', label: 'Message', type: 'text', required: true },
      ],
    },
  ]
}

function getSampleCSV(targetTable: 'nav_nodes' | 'edges'): string {
  if (targetTable === 'edges') {
    return `id,source,target
e3-9,n-3,n-9
e9-11,n-9,n-11`
  }

  const dynamicDefs = getDynamicNodeFieldDefs()
  const headers = ['id', 'label', 'kind', 'parent_id', ...dynamicDefs.map((f) => f.key)]
  const sampleRow1 = [
    'n-9',
    'Analytics Engine',
    'item',
    'n-domain-b',
    'Process',
    'ok',
    'ctm-app-03',
    '512',
    '1',
  ]
  const sampleRow2 = ['n-10', 'Domain D', 'folder', 'n-alpha', '', '', '', '', '2']
  return [
    headers.join(','),
    sampleRow1.slice(0, headers.length).join(','),
    sampleRow2.slice(0, headers.length).join(','),
  ].join('\n')
}

function downloadSampleCSV(targetTable: 'nav_nodes' | 'edges') {
  const content = getSampleCSV(targetTable)
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.setAttribute('download', `sample_${targetTable}.csv`)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

function parseCSV(text: string): Record<string, unknown>[] {
  const lines = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)

  if (lines.length < 2) return []

  const headers = lines[0].split(',').map((h) => h.trim())
  const rows: Record<string, unknown>[] = []

  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(',').map((val) => val.trim())
    const row: Record<string, unknown> = {}
    headers.forEach((header, index) => {
      const val = values[index] ?? ''
      if (val === '' || val === 'null' || val === 'undefined') {
        row[header] = null
      } else if (!isNaN(Number(val)) && val !== '') {
        row[header] = Number(val)
      } else {
        row[header] = val
      }
    })
    rows.push(row)
  }

  return rows
}

interface AdminModalProps {
  isOpen: boolean
  onClose: () => void
  onDataChanged: () => void
}

function AdminModal({ isOpen, onClose, onDataChanged }: AdminModalProps) {
  const [activeTab, setActiveTab] = useState<AdminTab>('modules')
  const [rows, setRows] = useState<Record<string, unknown>[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [searchFilter, setSearchFilter] = useState('')

  // Bulk CSV state
  const [bulkTable, setBulkTable] = useState<'nav_nodes' | 'edges'>('nav_nodes')
  const [csvFileName, setCsvFileName] = useState('')
  const [parsedRows, setParsedRows] = useState<Record<string, unknown>[]>([])
  const [importing, setImporting] = useState(false)
  const [importSuccessMsg, setImportSuccessMsg] = useState<string | null>(null)

  // Relational options cache
  const [relationalOptions, setRelationalOptions] = useState<
    Record<TableName, Array<{ value: string; label: string }>>
  >({
    modules: [],
    viewpoints: [],
    nav_nodes: [],
    edges: [],
    node_logs: [],
  })

  // Form State
  const [isFormOpen, setIsFormOpen] = useState(false)
  const [editingRow, setEditingRow] = useState<Record<string, unknown> | null>(null)
  const [formData, setFormData] = useState<Record<string, unknown>>({})
  const [submitting, setSubmitting] = useState(false)

  const schemas = useMemo(() => getSchemas(), [])
  const isBulkTab = activeTab === 'bulk_csv'
  const activeTableName: TableName = isBulkTab ? 'nav_nodes' : activeTab
  const schema = schemas.find((s) => s.name === activeTableName) ?? schemas[0]

  // Load relational lookup options
  const loadRelationalOptions = useCallback(async () => {
    try {
      const [modulesData, nodesData] = await Promise.all([
        fetchTableRows<{ id: string; label: string }>('modules'),
        fetchTableRows<{ id: string; label: string; kind: string }>('nav_nodes'),
      ])

      setRelationalOptions({
        modules: modulesData.map((m) => ({ value: m.id, label: `${m.label} (${m.id})` })),
        nav_nodes: nodesData.map((n) => ({
          value: n.id,
          label: `${n.label} (${n.id}) [${n.kind}]`,
        })),
        viewpoints: [],
        edges: [],
        node_logs: [],
      })
    } catch (err) {
      console.warn('Failed to load lookup options:', err)
    }
  }, [])

  // Load current table rows
  const loadTableData = useCallback(async () => {
    if (isBulkTab) return
    setLoading(true)
    setError(null)
    try {
      const data = await fetchTableRows(activeTableName)
      setRows(data)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoading(false)
    }
  }, [activeTableName, isBulkTab])

  useEffect(() => {
    if (isOpen) {
      loadRelationalOptions()
      loadTableData()
    }
  }, [isOpen, activeTab, loadRelationalOptions, loadTableData])

  if (!isOpen) return null

  const filteredRows = rows.filter((row) => {
    if (!searchFilter.trim()) return true
    const term = searchFilter.toLowerCase()
    return Object.values(row).some((val) => String(val ?? '').toLowerCase().includes(term))
  })

  const handleOpenAddForm = () => {
    setEditingRow(null)
    const initial: Record<string, unknown> = {}
    schema.columns.forEach((col) => {
      if (col.key === 'timestamp') {
        initial[col.key] = new Date().toISOString()
      } else if (col.type === 'number') {
        initial[col.key] = 0
      } else {
        initial[col.key] = ''
      }
    })
    setFormData(initial)
    setIsFormOpen(true)
  }

  const handleOpenEditForm = (row: Record<string, unknown>) => {
    setEditingRow(row)
    setFormData({ ...row })
    setIsFormOpen(true)
  }

  const handleDelete = async (row: Record<string, unknown>) => {
    const id = row[schema.primaryKey]
    if (!id) return
    if (!window.confirm(`Are you sure you want to delete entry "${id}" from ${schema.label}?`)) {
      return
    }

    try {
      await deleteTableRow(activeTableName, String(id))
      await loadTableData()
      await loadRelationalOptions()
      onDataChanged()
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : 'Failed to delete record')
    }
  }

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    try {
      if (editingRow) {
        const id = editingRow[schema.primaryKey]
        await updateTableRow(activeTableName, String(id), formData)
      } else {
        await createTableRow(activeTableName, formData)
      }
      setIsFormOpen(false)
      await loadTableData()
      await loadRelationalOptions()
      onDataChanged()
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : 'Failed to save record')
    } finally {
      setSubmitting(false)
    }
  }

  const handleCSVFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    setCsvFileName(file.name)
    setImportSuccessMsg(null)
    const reader = new FileReader()
    reader.onload = (event) => {
      const text = event.target?.result as string
      if (text) {
        const parsed = parseCSV(text)
        setParsedRows(parsed)
      }
    }
    reader.readAsText(file)
  }

  const handleBulkImportSubmit = async () => {
    if (parsedRows.length === 0) return
    setImporting(true)
    setError(null)
    try {
      const res = await bulkCreateRows(bulkTable, parsedRows)
      setImportSuccessMsg(
        `Successfully imported ${res.count} records into "${
          bulkTable === 'nav_nodes' ? 'Navigation Nodes' : 'Edges'
        }"!`
      )
      setParsedRows([])
      setCsvFileName('')
      await loadRelationalOptions()
      onDataChanged()
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to bulk import CSV rows')
    } finally {
      setImporting(false)
    }
  }

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/75 backdrop-blur-xs p-4">
      <div className="flex h-[88vh] w-full max-w-5xl flex-col overflow-hidden border border-border bg-surface shadow-2xl text-text">
        {/* Header Bar */}
        <div className="flex h-12 shrink-0 items-center justify-between border-b border-border bg-surface-sunken px-4">
          <div className="flex items-center gap-2">
            <span className="flex size-6 items-center justify-center bg-primary text-xs font-semibold text-primary-fg">
              DB
            </span>
            <h2 className="text-base font-semibold tracking-tight text-text">
              Database Admin Management
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="flex size-7 items-center justify-center text-text-secondary hover:bg-surface-hover hover:text-text"
            title="Close Admin Panel"
          >
            <Icon name="close" size={16} />
          </button>
        </div>

        {/* Table Selector Tabs */}
        <div className="flex shrink-0 border-b border-border bg-surface-sunken overflow-x-auto">
          {schemas.map((s) => {
            const isActive = s.name === activeTab
            return (
              <button
                key={s.name}
                type="button"
                onClick={() => {
                  setActiveTab(s.name)
                  setSearchFilter('')
                }}
                className={[
                  'flex items-center gap-2 border-r border-border px-4 py-2.5 text-sm transition-colors whitespace-nowrap',
                  isActive
                    ? 'bg-surface font-medium text-primary border-b-2 border-b-primary'
                    : 'text-text-secondary hover:bg-surface-hover hover:text-text',
                ].join(' ')}
              >
                {s.label}
              </button>
            )
          })}

          <button
            type="button"
            onClick={() => setActiveTab('bulk_csv')}
            className={[
              'flex items-center gap-2 border-r border-border px-4 py-2.5 text-sm transition-colors whitespace-nowrap font-medium',
              activeTab === 'bulk_csv'
                ? 'bg-surface text-primary border-b-2 border-b-primary'
                : 'text-accent hover:bg-surface-hover',
            ].join(' ')}
          >
            <span>📥 Bulk CSV Import</span>
          </button>
        </div>

        {/* Render Bulk CSV Section or Normal Table CRUD */}
        {isBulkTab ? (
          <div className="flex min-h-0 flex-1 flex-col overflow-auto p-5 space-y-6">
            <div className="border border-border bg-surface-sunken p-4 space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-3">
                <div>
                  <h3 className="text-sm font-semibold text-text">
                    Bulk CSV Import Data
                  </h3>
                  <p className="text-xs text-text-muted mt-0.5">
                    Upload CSV files to insert or update multiple Navigation Nodes or Edges simultaneously.
                  </p>
                </div>

                {/* Sample CSV Download Buttons */}
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => downloadSampleCSV('nav_nodes')}
                    className="flex items-center gap-1.5 border border-primary/40 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary hover:bg-primary/20 transition-colors"
                  >
                    <span>📥 Sample Nav Nodes CSV</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => downloadSampleCSV('edges')}
                    className="flex items-center gap-1.5 border border-primary/40 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary hover:bg-primary/20 transition-colors"
                  >
                    <span>📥 Sample Edges CSV</span>
                  </button>
                </div>
              </div>

              {/* Controls Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-text-secondary">
                    1. Select Target Table
                  </label>
                  <select
                    value={bulkTable}
                    onChange={(e) => {
                      setBulkTable(e.target.value as 'nav_nodes' | 'edges')
                      setParsedRows([])
                      setCsvFileName('')
                      setImportSuccessMsg(null)
                    }}
                    className="w-full border border-border bg-surface py-2 px-3 text-xs text-text focus:border-primary focus:outline-none"
                  >
                    <option value="nav_nodes">Navigation Nodes (nav_nodes)</option>
                    <option value="edges">Edges / Dependencies (edges)</option>
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-text-secondary">
                    2. Select CSV File
                  </label>
                  <input
                    type="file"
                    accept=".csv"
                    onChange={handleCSVFileSelect}
                    className="w-full border border-border bg-surface py-1.5 px-3 text-xs text-text file:mr-3 file:border-0 file:bg-surface-sunken file:px-2.5 file:py-1 file:text-xs file:font-semibold file:text-text hover:file:bg-surface-hover cursor-pointer"
                  />
                </div>
              </div>

              {csvFileName && (
                <div className="flex items-center justify-between text-xs text-text-muted bg-surface px-3 py-2 border border-border">
                  <span>
                    Loaded File: <strong className="text-text">{csvFileName}</strong>
                  </span>
                  <span>
                    Parsed Rows: <strong className="text-primary">{parsedRows.length}</strong>
                  </span>
                </div>
              )}
            </div>

            {/* Status Messages */}
            {importSuccessMsg && (
              <div className="p-3 text-xs bg-success-bg/20 border border-success-fg text-success-fg font-medium">
                {importSuccessMsg}
              </div>
            )}
            {error && (
              <div className="p-3 text-xs bg-danger-bg/20 border border-danger-fg text-danger-fg font-medium">
                Error: {error}
              </div>
            )}

            {/* Preview Table */}
            {parsedRows.length > 0 && (
              <div className="space-y-3 min-h-0 flex-1 flex flex-col">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-text-secondary">
                    CSV Data Preview ({parsedRows.length} rows ready for import)
                  </h4>
                  <button
                    type="button"
                    onClick={handleBulkImportSubmit}
                    disabled={importing}
                    className="bg-primary px-4 py-2 text-xs font-semibold text-primary-fg hover:opacity-90 disabled:opacity-50 transition-opacity"
                  >
                    {importing ? 'Importing Rows...' : `🚀 Import ${parsedRows.length} Rows into ${bulkTable}`}
                  </button>
                </div>

                <div className="overflow-x-auto border border-border max-h-72">
                  <table className="w-full text-left text-xs text-text">
                    <thead className="bg-surface-sunken text-text-secondary border-b border-border font-semibold uppercase">
                      <tr>
                        {Object.keys(parsedRows[0]).map((h) => (
                          <th key={h} className="px-3 py-2 border-r border-border last:border-r-0">
                            {h}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {parsedRows.slice(0, 50).map((row, idx) => (
                        <tr key={idx} className="hover:bg-surface-hover">
                          {Object.keys(parsedRows[0]).map((h) => (
                            <td key={h} className="px-3 py-1.5 border-r border-border last:border-r-0 truncate max-w-xs">
                              {String(row[h] ?? '--')}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {parsedRows.length > 50 && (
                  <p className="text-[11px] text-text-muted">
                    Showing first 50 rows of {parsedRows.length} total rows.
                  </p>
                )}
              </div>
            )}
          </div>
        ) : (
          <>
            {/* Action Toolbar for standard table */}
            <div className="flex h-12 shrink-0 items-center justify-between border-b border-border bg-surface px-4 gap-3">
              <div className="relative flex-1 max-w-sm">
                <Icon
                  name="search"
                  size={14}
                  className="absolute left-2.5 top-1/2 -translate-y-1/2 text-text-muted"
                />
                <input
                  type="text"
                  placeholder={`Search ${schema.label.toLowerCase()}...`}
                  value={searchFilter}
                  onChange={(e) => setSearchFilter(e.target.value)}
                  className="w-full border border-border bg-surface-sunken py-1.5 pl-8 pr-3 text-xs text-text placeholder:text-text-muted focus:border-primary focus:outline-none"
                />
              </div>

              <button
                type="button"
                onClick={handleOpenAddForm}
                className="flex items-center gap-1.5 bg-primary px-3 py-1.5 text-xs font-medium text-primary-fg hover:opacity-90 transition-opacity"
              >
                <Icon name="plus" size={14} />
                <span>Add New Record</span>
              </button>
            </div>

            {/* Table Content Area */}
            <div className="min-h-0 flex-1 overflow-auto p-4">
              {loading ? (
                <div className="flex h-40 items-center justify-center text-sm text-text-muted">
                  Loading database rows...
                </div>
              ) : error ? (
                <div className="p-4 text-sm text-danger-fg bg-danger-bg/10 border border-danger-fg/30">
                  Error loading table data: {error}
                </div>
              ) : filteredRows.length === 0 ? (
                <div className="flex h-40 flex-col items-center justify-center gap-2 text-sm text-text-muted">
                  <p>No records found in table "{schema.label}".</p>
                  <button
                    type="button"
                    onClick={handleOpenAddForm}
                    className="text-xs text-primary underline underline-offset-2"
                  >
                    Click here to add the first record
                  </button>
                </div>
              ) : (
                <div className="overflow-x-auto border border-border">
                  <table className="w-full text-left text-xs text-text">
                    <thead className="bg-surface-sunken text-text-secondary border-b border-border font-semibold uppercase tracking-wider">
                      <tr>
                        {schema.columns.map((col) => (
                          <th key={col.key} className="px-3 py-2 border-r border-border last:border-r-0">
                            {col.label}
                          </th>
                        ))}
                        <th className="px-3 py-2 text-right w-24">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {filteredRows.map((row, idx) => {
                        const rowKey = String(row[schema.primaryKey] ?? idx)
                        return (
                          <tr key={rowKey} className="hover:bg-surface-hover transition-colors">
                            {schema.columns.map((col) => (
                              <td key={col.key} className="px-3 py-2 border-r border-border last:border-r-0 max-w-xs truncate">
                                {String(row[col.key] ?? '--')}
                              </td>
                            ))}
                            <td className="px-3 py-2 text-right">
                              <div className="flex items-center justify-end gap-1">
                                <button
                                  type="button"
                                  onClick={() => handleOpenEditForm(row)}
                                  className="p-1 text-text-secondary hover:text-primary hover:bg-surface-sunken"
                                  title="Edit Row"
                                >
                                  <Icon name="edit" size={14} />
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleDelete(row)}
                                  className="p-1 text-text-secondary hover:text-danger-fg hover:bg-surface-sunken"
                                  title="Delete Row"
                                >
                                  <Icon name="close" size={14} />
                                </button>
                              </div>
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </>
        )}

        {/* Footer info bar */}
        <div className="flex h-8 shrink-0 items-center justify-between border-t border-border bg-surface-sunken px-4 text-xs text-text-muted">
          <span>
            Active View: <strong className="text-text">{isBulkTab ? 'Bulk CSV Import' : schema.label}</strong> | Total records:{' '}
            <strong className="text-text">{isBulkTab ? parsedRows.length : rows.length}</strong>
          </span>
          <span>SQLite Database: api/database.sqlite</span>
        </div>
      </div>

      {/* Form Modal for Create / Edit */}
      {isFormOpen && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/70 p-4">
          <div className="w-full max-w-lg border border-border bg-surface p-5 shadow-2xl text-text">
            <div className="flex items-center justify-between border-b border-border pb-3 mb-4">
              <h3 className="text-base font-semibold">
                {editingRow ? `Edit ${schema.label} Record` : `Add New ${schema.label} Record`}
              </h3>
              <button
                type="button"
                onClick={() => setIsFormOpen(false)}
                className="text-text-muted hover:text-text"
              >
                <Icon name="close" size={16} />
              </button>
            </div>

            <form onSubmit={handleFormSubmit} className="space-y-3 max-h-[70vh] overflow-y-auto pr-1">
              {schema.columns.map((col) => {
                if (col.autoGenerated && !editingRow) {
                  return null
                }

                const isPrimaryKeyEdit = editingRow && col.key === schema.primaryKey
                const options = col.relationalTable
                  ? relationalOptions[col.relationalTable] || []
                  : col.options || []

                return (
                  <div key={col.key} className="space-y-1">
                    <label className="block text-xs font-medium text-text-secondary">
                      {col.label}{' '}
                      {col.required && <span className="text-danger-fg">*</span>}
                    </label>

                    {col.type === 'select' || col.relationalTable ? (
                      <select
                        value={String(formData[col.key] ?? '')}
                        onChange={(e) =>
                          setFormData({ ...formData, [col.key]: e.target.value })
                        }
                        disabled={Boolean(isPrimaryKeyEdit)}
                        required={col.required}
                        className="w-full border border-border bg-surface-sunken py-1.5 px-2.5 text-xs text-text focus:border-primary focus:outline-none"
                      >
                        <option value="">
                          {col.required ? '-- Select Option --' : '-- None (Optional) --'}
                        </option>
                        {options.map((opt) => (
                          <option key={opt.value} value={opt.value}>
                            {opt.label}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type={col.type === 'number' ? 'number' : 'text'}
                        value={String(formData[col.key] ?? '')}
                        onChange={(e) =>
                          setFormData({
                            ...formData,
                            [col.key]:
                              col.type === 'number'
                                ? e.target.value === ''
                                  ? ''
                                  : Number(e.target.value)
                                : e.target.value,
                          })
                        }
                        disabled={Boolean(isPrimaryKeyEdit)}
                        required={col.required}
                        className="w-full border border-border bg-surface-sunken py-1.5 px-2.5 text-xs text-text focus:border-primary focus:outline-none disabled:opacity-50"
                      />
                    )}
                  </div>
                )
              })}

              <div className="flex items-center justify-end gap-2 border-t border-border pt-4 mt-5">
                <button
                  type="button"
                  onClick={() => setIsFormOpen(false)}
                  className="border border-border bg-surface-sunken px-3 py-1.5 text-xs text-text-secondary hover:text-text"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="bg-primary px-4 py-1.5 text-xs font-medium text-primary-fg hover:opacity-90 disabled:opacity-50"
                >
                  {submitting ? 'Saving...' : editingRow ? 'Update Record' : 'Create Record'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default AdminModal
